"use strict";

function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SelectedOption = exports.OrderTypeWrapper = exports.OrderTypeBoxGroup = exports.OrderType = exports.OrderItemWraper = exports.OrderItem = exports.OrderDescription = exports.Option = exports.ItemContent = exports.ContentOption = void 0;
var _styledComponents = _interopRequireWildcard(require("styled-components"));
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject10, _templateObject11;
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function _getRequireWildcardCache(e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != _typeof(e) && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && Object.prototype.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var Option = exports.Option = _styledComponents.default.div(_templateObject || (_templateObject = _taggedTemplateLiteral(["\n  display: flex;\n  align-items: center;\n  svg {\n    min-width: 14px;\n    margin-right: 5px;\n    ", "\n  }  \n"])), function (props) {
  var _props$theme;
  return ((_props$theme = props.theme) === null || _props$theme === void 0 ? void 0 : _props$theme.rtl) && (0, _styledComponents.css)(_templateObject2 || (_templateObject2 = _taggedTemplateLiteral(["\n      margin-left: 5px;\n      margin-right: 0px;\n    "])));
});
var OrderTypeWrapper = exports.OrderTypeWrapper = _styledComponents.default.span(_templateObject3 || (_templateObject3 = _taggedTemplateLiteral(["\n  display: flex;\n  justify-content: center;\n  width: 100%;\n"])));
var SelectedOption = exports.SelectedOption = _styledComponents.default.p(_templateObject4 || (_templateObject4 = _taggedTemplateLiteral(["  \n  margin: 0;\n  max-width: 60px;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n  @media (min-width: 380px) {\n      max-width: initial;\n  }\n"])));
var ContentOption = exports.ContentOption = (0, _styledComponents.default)(SelectedOption)(_templateObject5 || (_templateObject5 = _taggedTemplateLiteral(["\n  max-width: 80px;\n"])));
var OrderTypeBoxGroup = exports.OrderTypeBoxGroup = _styledComponents.default.div(_templateObject6 || (_templateObject6 = _taggedTemplateLiteral(["\n  display: flex;\n  flex-wrap: wrap;\n  width: 100%;\n  @media (min-width: 1200px) {\n    max-width: 1230px;\n  }\n  @media (min-width: 1405px) {\n    max-width: 1420px;\n  }\n"])));
var OrderItem = exports.OrderItem = _styledComponents.default.div(_templateObject7 || (_templateObject7 = _taggedTemplateLiteral(["\n  display:flex;\n  justify-content: center;\n  box-sizing: border-box;\n  width: 100%;\n  padding: 15px;\n  cursor: pointer;\n\n  @media (min-width: 576px) {\n    width: 50%;\n  }\n  @media (min-width: 850px) {\n    width: 20%;\n    padding: 10px;\n  }\n"])));
var OrderItemWraper = exports.OrderItemWraper = _styledComponents.default.div(_templateObject8 || (_templateObject8 = _taggedTemplateLiteral(["\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  background: #FFFFFF;\n  box-shadow: 1px 4px 10px rgb(0 0 0 / 12%);\n  border-radius: 20px;\n  padding: 35px 25px;\n  @media (min-width: 850px) {\n    padding: 25px 15px;\n  }\n  @media (min-width: 1420px) {\n    padding: 35px 20px;\n  }\n"])));
var OrderType = exports.OrderType = _styledComponents.default.div(_templateObject9 || (_templateObject9 = _taggedTemplateLiteral(["\n  display: flex;\n  justify-content: center;\n  margin-bottom: 15px;\n  svg {\n    min-width: 14px;\n    font-size: 25px;\n  }\n  svg path{    \n    fill: ", ";\n  }\n"])), function (props) {
  return props.theme.colors.primary;
});
var ItemContent = exports.ItemContent = _styledComponents.default.div(_templateObject10 || (_templateObject10 = _taggedTemplateLiteral(["\n  font-style: normal;\n  font-weight: bold;\n  font-size: 20px;\n  line-height: 24px;\n  margin: 0 15px;\n  @media (min-width: 1024px) {\n    font-size: 18px;   \n    margin: 0 7px;\n  }\n  @media (min-width: 1450px) {\n    font-size: 25px;    \n  }\n"])));
var OrderDescription = exports.OrderDescription = _styledComponents.default.div(_templateObject11 || (_templateObject11 = _taggedTemplateLiteral(["\n  font-size: 12px;\n  @media (min-width: 1405px) {\n    font-size: 14px;\n  }\n"])));