"use strict";

function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TimeListWrapper = exports.TimeItem = exports.LayoutContainer = exports.ClosedBusinessMsg = exports.CalendarWrapper = void 0;
var _styledComponents = _interopRequireWildcard(require("styled-components"));
var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7;
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function _getRequireWildcardCache(e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != _typeof(e) && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && Object.prototype.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
var LayoutContainer = exports.LayoutContainer = _styledComponents.default.div(_templateObject || (_templateObject = _taggedTemplateLiteral(["\n  display: flex;\n  flex-direction: column;\n\n  @media (min-width: 768px) {\n    flex-direction: row;\n    justify-content: space-between;\n    > div {\n      width: calc(50% - 10px);\n    }\n  }\n"])));
var CalendarWrapper = exports.CalendarWrapper = _styledComponents.default.div(_templateObject2 || (_templateObject2 = _taggedTemplateLiteral(["\n  display: flex;\n  justify-content: center;\n  flex-direction: column;\n  align-items: center;\n  padding: 17px 15px 3px 15px;\n  border: 1px solid #E9ECEF;\n  box-sizing: border-box;\n  border-radius: 7.6px;\n\n  input {\n    padding: 10px;\n    border: 1px solid #DEE2E6;\n    box-sizing: border-box;\n    border-radius: 7.6px;\n    outline: none;\n  }\n\n  .react-calendar {\n    border: none;\n    width: 100%;\n\n    .react-calendar__tile--active,\n    .react-calendar__tile:enabled:focus {\n      /* background: ", "; */\n      background: transparent;\n\n      abbr {\n        background: #E9F2FE;\n        color: #344050;\n      }\n    }\n\n    .react-calendar__tile:enabled:hover {\n      background: transparent;\n\n      abbr {\n        background: #EFEFEF;\n        color: #344050;\n      }\n    }\n\n    .react-calendar__tile--now {\n      background: transparent;\n    }\n\n    .react-calendar__month-view__weekdays {\n      font-size: 12px;\n      color: #909BA9;\n      font-weight: normal;\n      text-transform: capitalize;\n      abbr {\n        text-decoration: none;\n      }\n    }\n\n    .react-calendar__month-view__days__day {\n      font-size: 12px;\n      color: #344050;\n      abbr {\n        width: 20px;\n        height: 20px;\n        display: flex;\n        justify-content: center;\n        align-items: center;\n        border-radius: 50%;\n\n        @media (min-width: 350px) {\n          width: 34px;\n          height: 32px;\n        }\n      }\n    }\n\n    .react-calendar__tile:disabled {\n      background-color: transparent;\n      color: ", ";\n      cursor: not-allowed;\n    }\n\n    .react-calendar__navigation {\n      button {\n        background: transparent!important;\n        color: #748194;\n\n        svg {\n          font-size: 24px;\n\n          ", "\n        }\n\n        &:disabled {\n          cursor: not-allowed;\n        }\n\n        span {\n          white-space: nowrap;\n          text-overflow: ellipsis;\n          overflow: hidden;\n          width: 100%;\n          display: inline-block;\n\n          @media (min-width: 768px) {\n            width: auto;\n            display: initial;\n          }\n        }\n      }\n\n      .react-calendar__navigation__prev2-button,\n      .react-calendar__navigation__next2-button {\n        display: none;\n      }\n    }\n  }\n"])), function (props) {
  var _props$theme;
  return (_props$theme = props.theme) === null || _props$theme === void 0 ? void 0 : _props$theme.colors.primaryContrast;
}, function (props) {
  var _props$theme2;
  return (_props$theme2 = props.theme) === null || _props$theme2 === void 0 ? void 0 : _props$theme2.colors.disabled;
}, function (props) {
  return props.theme.rtl && (0, _styledComponents.css)(_templateObject3 || (_templateObject3 = _taggedTemplateLiteral(["\n            transform: rotateZ(180deg);\n          "])));
});
var TimeListWrapper = exports.TimeListWrapper = _styledComponents.default.div(_templateObject4 || (_templateObject4 = _taggedTemplateLiteral(["\n  display: flex;\n  flex-wrap: wrap;\n  max-height: 425px;\n  overflow: auto;\n  padding: 17px 15px 3px 15px;\n  border: 1px solid #E9ECEF;\n  box-sizing: border-box;\n  border-radius: 7.6px;\n  margin-top: 20px;\n\n  @media (min-width: 768px) {\n    margin-top: 0;\n  }\n"])));
var TimeItem = exports.TimeItem = _styledComponents.default.div(_templateObject5 || (_templateObject5 = _taggedTemplateLiteral(["\n  cursor: pointer;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background: #E9ECEF;\n  border-radius: 7.6px;\n  padding: 5px 15px;\n  margin: 12px;\n  width: calc(50% - 24px);\n  min-width: calc(50% - 24px);\n  box-sizing: border-box;\n  user-select: none;\n\n  ", "\n\n  span {\n    font-size: 14px;\n    white-space: nowrap;\n  }\n"])), function (_ref) {
  var active = _ref.active;
  return active && (0, _styledComponents.css)(_templateObject6 || (_templateObject6 = _taggedTemplateLiteral(["\n    background: #F5F9FF;\n    color: ", ";\n  "])), function (props) {
    return props.theme.colors.primary;
  });
});
var ClosedBusinessMsg = exports.ClosedBusinessMsg = _styledComponents.default.div(_templateObject7 || (_templateObject7 = _taggedTemplateLiteral(["\n  text-align: center;\n  font-size: 16px;\n  width: 100%;\n"])));